language: minimal
sudo: false

matrix:
  include:
    - name: "python-3.6-pypi"
      env: PY=3.6 PYSAL_PYPI=true PYSAL_PLUS=false
    - name: "python-3.6-pypi-plus"
      env: PY=3.6 PYSAL_PYPI=true PYSAL_PLUS=true
    - name: "python-3.7-pypi"
      env: PY=3.7 PYSAL_PYPI=true PYSAL_PLUS=false
    - name: "python-3.7-pypi-plus"
      env: PY=3.7 PYSAL_PYPI=true PYSAL_PLUS=true
    - name: "python-3.8-pypi"
      env: PY=3.8 PYSAL_PYPI=true PYSAL_PLUS=false
    - name: "python-3.8-pypi-plus"
      env: PY=3.8 PYSAL_PYPI=true PYSAL_PLUS=true
    - name: "tarball-pypi"
      env: PY=3.8 PYSAL_PYPI=true PYSAL_PLUS=false
    - name: "python-3.6"
      env: PY=3.6 PYSAL_PYPI=false PYSAL_PLUS=false
    - name: "python-3.6-plus"
      env: PY=3.6 PYSAL_PYPI=false PYSAL_PLUS=true
    - name: "python-3.7"
      env: PY=3.7 PYSAL_PYPI=false PYSAL_PLUS=false
    - name: "python-3.7-plus"
      env: PY=3.7 PYSAL_PYPI=false PYSAL_PLUS=true
    - name: "python-3.8"
      env: PY=3.8 PYSAL_PYPI=false PYSAL_PLUS=false
    - name: "python-3.8-plus"
      env: PY=3.8 PYSAL_PYPI=false PYSAL_PLUS=true
  allow_failures:
    - name: "python-3.6"
      env: PY=3.6 PYSAL_PYPI=false PYSAL_PLUS=false
    - name: "python-3.6-plus"
      env: PY=3.6 PYSAL_PYPI=false PYSAL_PLUS=true
    - name: "python-3.7"
      env: PY=3.7 PYSAL_PYPI=false PYSAL_PLUS=false
    - name: "python-3.7-plus"
      env: PY=3.7 PYSAL_PYPI=false PYSAL_PLUS=true
    - name: "python-3.8"
      env: PY=3.8 PYSAL_PYPI=false PYSAL_PLUS=false
    - name: "python-3.8-plus"
      env: PY=3.8 PYSAL_PYPI=false PYSAL_PLUS=true

before_install:
  - |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update --quiet conda
    conda config --add channels conda-forge --force
    conda config --set channel_priority strict
    conda config --set safety_checks disabled
    conda create --name TEST python=$PY --file requirements.txt --file requirements_dev.txt --file requirements_tests.txt
    source activate TEST
    conda info --all

install:
  - pip install -e . --no-deps --force-reinstall
  - if [ "$PYSAL_PYPI" == true ]; then
        echo 'testing conda libpysal';
        conda install --yes libpysal;
    else echo 'testing git libpysal';
        git clone https://github.com/pysal/libpysal.git;
        cd libpysal;
        pip install .;
        cd ../;
    fi;
  - if [ "$PYSAL_PLUS" == true ]; then
        echo 'plus testing';
        conda install --yes --file requirements_plus.txt;
    fi;

script:
  - python -c 'import libpysal; libpysal.examples.load_example("newHaven")'
  - if [[ $TRAVIS_JOB_NAME == python-* ]]; then
      travis_wait 45 nosetests --verbose --with-coverage --with-doctest --cover-package=spaghetti;
    fi

  - if [[ $TRAVIS_JOB_NAME == tarball* ]]; then
      pip wheel . -w dist --no-deps;
      twine check dist/*;
    fi

notifications:
    email:
        recipients:
          - sjsrey+travis@gmail.com
          - levi.john.wolf+travis@gmail.com
          - jgaboardi+travis@gmail.com
        on_success: change
        on_failure: change

after_success:
  - coveralls
